name: Check PHP code style

on:
  push:
    paths:
      - '**.php'
      - '.github/workflows/fix-php-code-style-issues.yml'
  pull_request:
    paths:
      - '**.php'
      - '.github/workflows/fix-php-code-style-issues.yml'

jobs:
  php-code-styling:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Check code style with Pint
        run: vendor/bin/pint --test
